<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-01-21T18:38:38Z" name="Default suite" finished-at="2025-01-21T18:38:38Z" duration-ms="28">
    <groups>
    </groups>
    <test started-at="2025-01-21T18:38:38Z" name="Default test" finished-at="2025-01-21T18:38:38Z" duration-ms="28">
      <class name="dataDrivenTesting.Login">
        <test-method signature="practice(java.lang.String, java.lang.String)[pri:0, instance:dataDrivenTesting.Login@1ca3b418]" started-at="2025-01-22T00:08:38Z" name="practice" data-provider="logindata" finished-at="2025-01-22T00:08:38Z" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void dataDrivenTesting.Login.practice(java.lang.String,java.lang.String) throws org.apache.poi.EncryptedDocumentException,java.io.IOException requires a @DataProvider named : logindata]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void dataDrivenTesting.Login.practice(java.lang.String,java.lang.String) throws org.apache.poi.EncryptedDocumentException,java.io.IOException requires a @DataProvider named : logindata
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- practice -->
      </class> <!-- dataDrivenTesting.Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
